name: Enforce PR Format

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  enforce-pr-format:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Description
        id: pr-description
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prDescription = context.payload.pull_request.body;
            const ticketPattern = /^IAM-\d+/;
            if (!ticketPattern.test(prDescription)) {
              core.setFailed('PR description does not reference an IAM or Jira ticket.');
            }
