name: Enforce PR Title Format

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  enforce-pr-title-format:
    runs-on: ubuntu-latest

    steps:
      - name: Debug PR Title
        run: echo "PR Title: ${{ github.event.pull_request.title }}"
      
      - name: Debug Regex Pattern
        run: echo "Regex Pattern: /^(IAM-\d+|JIRA-\d+): .+$/"
      
      - name: Check PR Title
        id: pr-title
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prTitle = context.payload.pull_request.title;
            const titlePattern = /^(IAM-\d+|JIRA-\d+): .+$/;
            console.log(`PR Title: ${prTitle}`);
            console.log(`Regex Match: ${titlePattern.test(prTitle)}`);
            if (!titlePattern.test(prTitle)) {
              core.setFailed('PR title does not match the required format. It should start with "IAM-<number>:" or "JIRA-<number>:" followed by a description.');
            }

              core.setFailed('PR title does not match the required format. It should start with "IAM-<number>:" or "JIRA-<number>:" followed by a description.');
            }
